### PR TITLE
use builtin `os.TempDir()` instead of `"/tmp"`

### PR DESCRIPTION
**Pull request by drgarcia1986**
This change is [Reviewable](https://reviewable.io/reviews/luizalabs/teresa-cli/39)

### CODE REVIEW

**Comment by alexguerra-luizalabs** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/constants.go, line 32 at r1](https://reviewable.io:443/reviews/luizalabs/teresa-cli/39#-KcsltDeRKLE-x7QgWF9:-KcsltDeRKLE-x7QgWFA:bkuj3dx) ([raw file](https://github.com/luizalabs/teresa-cli/blob/a588b6e5c0d478e59642270b7b1bc86fe7a9b926/cmd/constants.go#L32)):*
> ```Go
> )
> 
> var archiveTempFolder = os.TempDir()
> ```

I think we can remove `archiveTempFolder` completely, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/luizalabs/teresa-cli/39)*

**Comment by alexguerra-luizalabs** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/luizalabs/teresa-cli/39)*

**Comment by drgarcia1986** [comment]
@alexguerra-luizalabs removed 👍

**Comment by alexguerra-luizalabs** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cmd/constants.go, line 32 at r1](https://reviewable.io:443/reviews/luizalabs/teresa-cli/39#-KcsltDeRKLE-x7QgWF9:-KcwcQ0LsBoj5JlnNzsA:b32w0x) ([raw file](https://github.com/luizalabs/teresa-cli/blob/a588b6e5c0d478e59642270b7b1bc86fe7a9b926/cmd/constants.go#L32)):*
<details><summary><i>Previously, alexguerra-luizalabs (Alex Guerra) wrote…</i></summary><blockquote>

I think we can remove `archiveTempFolder` completely, right?
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/luizalabs/teresa-cli/39#-:-Kcwc5M5anj7i7EMBfVg:bnfp4nl)*

**Comment by lucianokadoya-luizalabs** [comment]
:+1:

**Pull request merged**
